### ISSUE TITLE
(1.20.1) Crash on Startup

### ISSUE THREAD

**Issue by Diogoess** [SiverDX/quality_food#31]
The mod seems to be crashing, and the log suspects it's something to do with BCLib? I'm using the latest version of both mods, game was running fine before installing Quality food. 

[crash-2024-10-24_17.22.23-client.txt](https://github.com/user-attachments/files/17509922/crash-2024-10-24_17.22.23-client.txt)

**Comment by SiverDX** [comment]
I don't think this is related to quality food

There is no mention of it and the part that causes the error (related to item models) is something quality food has no interaction with

**Comment by Diogoess** [comment]
It's strange, the game starts without the mod just fine. Should I bring this up to the BCLib developer?

**Comment by SiverDX** [comment]
I tried it with Better Nether + BCLib just now and no issue
Seems related to your modpack

You can try posting the `latest.log` maybe it has some info
Can't say whether you should bring it up to them or not

**Comment by Diogoess** [comment]
Alright, Here goes 

[latest.log](https://github.com/user-attachments/files/17510250/latest.log)

**Comment by SiverDX** [comment]
try updating harvest with ease to the latest version

```
java.lang.NoClassDefFoundError: it/crystalnest/harvest_with_ease/api/event/HarvestEvents$HarvestDropsEvent
	at de.cadentem.quality_food.QualityFood.<init>(QualityFood.java:42) ~[quality_food-1.20.1-2.0.3-all%2017.10.49.jar%23873!/:2.0.3]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23976!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23975!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: it.crystalnest.harvest_with_ease.api.event.HarvestEvents$HarvestDropsEvent
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 13 more
```

**Comment by Diogoess** [comment]
It worked!!! Thank you so much
